name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build-74:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        load: true
        context: .
        file: dist/7.4/Dockerfile
        tags: |
          n30fly/php-fpm:7.4
          n30fly/php-fpm:7.4.27
    - name: Run tests
      run: |
        curl -sLO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && \
        chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test && \
        container-structure-test test --image n30fly/php-fpm:7.4 --config tests/7.4/test.yaml
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: dist/7.4/Dockerfile
        tags: |
          n30fly/php-fpm:7.4
          n30fly/php-fpm:7.4.27
