name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build-71:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        context: .
        file: dist/7.1/Dockerfile
        tags: |
          n30fly/php-fpm:7.1
          n30fly/php-fpm:7.1.33
          ghcr.io/n30fly/php-fpm:7.1
          ghcr.io/n30fly/php-fpm:7.1.33
  build-74:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        load: true
        context: .
        file: dist/7.4/Dockerfile
        tags: |
          n30fly/php-fpm:7.4
          n30fly/php-fpm:7.4.33
    - name: Run tests
      run: |
        curl -sLO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && \
        chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test && \
        container-structure-test test --image n30fly/php-fpm:7.4 --config tests/7.4/test.yaml
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        context: .
        file: dist/7.4/Dockerfile
        tags: |
          n30fly/php-fpm:7.4
          n30fly/php-fpm:7.4.33
          ghcr.io/n30fly/php-fpm:7.4
          ghcr.io/n30fly/php-fpm:7.4.33
  build-81:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        context: .
        file: dist/8.1/Dockerfile
        tags: |
          n30fly/php-fpm:8.1
          n30fly/php-fpm:8.1.23
          ghcr.io/n30fly/php-fpm:8.1
          ghcr.io/n30fly/php-fpm:8.1.23
